project_id = "cwkknbcygbuouuctwujh"

[functions.compare-documents]
verify_jwt = false

[functions.extract-document]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.improve-text]
verify_jwt = false

[functions.send-disturbance-report]
verify_jwt = false
